# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mdview < Formula
  desc "Live-reloading Markdown viewer for the terminal"
  homepage "https://github.com/vashuteotia123/mdview"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vashuteotia123/mdview/releases/download/v0.1.0/mdview_darwin_amd64.tar.gz"
      sha256 "825ed69dcd248b3ea05fe7be3f3f843b2e358446ce6d75674f27d752ab861077"

      define_method(:install) do
        bin.install "mdview"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vashuteotia123/mdview/releases/download/v0.1.0/mdview_darwin_arm64.tar.gz"
      sha256 "f460e15ce485ffd93be2ec722d4857b1ff8200c4928118e22e6678cd1cde3351"

      define_method(:install) do
        bin.install "mdview"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vashuteotia123/mdview/releases/download/v0.1.0/mdview_linux_amd64.tar.gz"
      sha256 "725a435367da363bb2caa01495517afc5cda6835c640afe92fbaee602e3c3952"
      define_method(:install) do
        bin.install "mdview"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vashuteotia123/mdview/releases/download/v0.1.0/mdview_linux_arm64.tar.gz"
      sha256 "883d54eecc818a1287da67743196b2f94cddc0e60c9b125d6ec47c90ab507e70"
      define_method(:install) do
        bin.install "mdview"
      end
    end
  end
end
